### ISSUE TITLE
Create user.

### ISSUE THREAD

**Issue by GrumpyMeow** [larsw/adlds-docker#1]
It took me a few hours to find out how to create AD objects from the command-line (within the container). Apparently it's important to connect to AD LDS as the ADLDSAdmin user.

I hope the following snippet helps others along:

```
$secpasswd = ConvertTo-SecureString "4DLD$4dmin2017!" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ("ADLDSAdmin", $secpasswd)

New-ADUser GlenJohn -Type iNetOrgPerson -Path "DC=local" -server localhost:389 -authtype 1 -credential $mycreds
```

**Comment by larsw** [comment]
Added to a new README.md. Thanks.
